import json, uuid

op_eds = [
    {
        "source_name": "Dr. Tarık Yılmaz",
        "title": "Küresel Enflasyon ve Tarımsal Girdilerdeki Fiyat Makası",
        "title_en": "Global Inflation and the Price Gap in Agricultural Inputs",
        "content": "<p>Son yıllarda küresel tedarik zincirlerinde yaşanan kırılmalar ve enerji fiyatlarındaki dramatik artışlar, tarımsal üretimin en temel girdilerinden biri olan gübre sektörünü derinden sarsmıştır. Özellikle doğalgaz fiyatlarındaki dalgalanmalar, azotlu gübre üretim maliyetlerini doğrudan yukarı çekmiş ve bu durum dünya genelinde bir arz krizini tetiklemiştir. Türkiye gibi ithalata bağımlılığı yüksek olan gelişmekte olan ülkelerde ise bu krizin yansımaları çiftçinin sırtındaki maliyet yükünü katlanamaz hale getirmiştir.</p><p>Tarımsal üretim süreçlerinde gübre kullanımının azaltılması, doğrudan birim alandan alınan verimi düşürmekte ve bu durum orta vadede gıda enflasyonunu körüklemektedir. Üreticilerimizin yüksek girdi maliyetleri karşısında gübreleme periyotlarından feragat etmek zorunda kalması, hem rekolte kalitesini düşürmekte hem de iç pazarda arz yetersizliklerine yol açmaktadır. Bu durum, sürdürülebilir gıda güvenliğimizi doğrudan tehdit eden bir makroekonomik risk haline dönüşmüştür.</p><p>Çözüm noktasında ise devlet desteklerinin ve tarımsal sübvansiyonların etkinliği kritik bir rol oynamaktadır. Cari gübre fiyatları ile verilen destekler arasındaki makas açıldıkça, küçük aile işletmelerinin üretimde kalması zorlaşmaktadır. Finansal açıdan üreticiye nefes aldıracak düşük faizli işletme kredileri ve girdi bazlı nakdi desteklerin zamanında ödenmesi, önümüzdeki hasat dönemlerinin kaderini belirleyecektir.</p><p>Uzun vadede ise kimyasal gübrelere olan bağımlılığı azaltacak alternatif tarım politikalarına yönelmemiz kaçınılmazdır. Organik ve organomineral gübre üretim tesislerinin yerli imkanlarla desteklenmesi, hem cari açığı azaltacak hem de toprak yapımızın uzun vadede korunmasını sağlayacaktır. Türkiye, sahip olduğu biyokütle potansiyeliyle bu dönüşümü gerçekleştirebilecek güçtedir; yeter ki doğru planlama ve teşvik mekanizmaları hayata geçirilsin.</p>",
        "content_en": "<p>In recent years, disruptions in global supply chains and dramatic increases in energy prices have deeply shaken the fertilizer sector, one of the most fundamental inputs of agricultural production. Especially fluctuations in natural gas prices have directly pushed up the production costs of nitrogenous fertilizers, triggering a supply crisis worldwide. In developing countries highly dependent on imports like Turkey, the reflections of this crisis have made the cost burden on the farmer\'s back unbearable.</p><p>Reducing fertilizer use in agricultural production processes directly lowers the yield per unit area, and this situation fuels food inflation in the medium term. The fact that our producers have to sacrifice fertilization periods in the face of high input costs not only reduces the harvest quality but also leads to supply inadequacies in the domestic market. This situation has turned into a macroeconomic risk that directly threatens our sustainable food security.</p><p>At the point of solution, the effectiveness of state supports and agricultural subsidies plays a critical role. As the gap between current fertilizer prices and the supports provided widens, it becomes difficult for small family businesses to stay in production. Low-interest business loans that will give the producer a breather financially and the timely payment of input-based cash supports will determine the fate of the upcoming harvest periods.</p><p>In the long run, it is inevitable for us to turn to alternative agricultural policies that will reduce our dependence on chemical fertilizers. Supporting organic and organomineral fertilizer production facilities with domestic resources will both reduce the current account deficit and ensure the long-term protection of our soil structure. Turkey has the power to realize this transformation with its biomass potential; as long as the right planning and incentive mechanisms are implemented.</p>",
        "summary": "Gübre krizinin makroekonomik etkileri ve alternatif tarım politikalarının önemi.",
        "summary_en": "Macroeconomic impacts of the fertilizer crisis and the importance of alternative agricultural policies.",
        "image_url": "https://images.unsplash.com/photo-1625246333195-78d9c38ad49f?w=900&auto=format&fit=crop&q=80",
    },
    {
        "source_name": "Zeynep Aksoy",
        "title": "Akıllı Sulama ve Su Stresiyle Mücadele",
        "title_en": "Smart Irrigation and Combating Water Stress",
        "content": "<p>Küresel iklim değişikliği ve buna bağlı olarak artan kuraklık riskleri, tatlı su kaynaklarımızın üzerindeki baskıyı her geçen gün artırıyor. Dünyada tüketilen suyun yaklaşık yüzde 70\'inin tarımsal sulamada kullanıldığı göz önüne olduğunda, tarımda su verimliliğini sağlamanın sadece sektörel bir gereklilik değil, yaşamsal bir zorunluluk olduğu açıkça görülmektedir. Vahşi sulama yöntemlerinden vazgeçip suyun her damlasını hesaplayan akıllı sistemlere geçiş, sürdürülebilirliğin anahtarıdır.</p><p>Akıllı sulama teknolojileri; toprak nem sensörleri, meteorolojik istasyonlar ve yapay zeka destekli karar destek mekanizmaları ile donatılmış modern sistemlerdir. Bu sistemler sayesinde bitkinin ihtiyaç duyduğu su miktarı anlık olarak analiz edilmekte ve tam zamanında, doğru miktarda sulama yapılmaktadır. Böylece hem su israfının önüne geçilmekte hem de aşırı sulamadan kaynaklanan taban suyu yükselmesi ve tuzlanma gibi toprak kalitesini bozan faktörler engellenmektedir.</p><p>Dijitalleşmenin tarımdaki bu uygulamaları, ilk yatırım maliyetleri nedeniyle küçük üreticiler için erişilmesi güç görünebilir. Ancak kooperatifleşme ve devlet teşvikleri aracılığıyla bu teknolojilerin yaygınlaştırılması mümkündür. Damla sulama ve basınçlı sulama altyapısına geçiş yapan çiftçilerimizin enerji maliyetlerinde sağladığı tasarruf, bu yatırımların kendini çok kısa sürede amorti ettiğini göstermektedir.</p><p>Gelecek nesillere verimli topraklar ve yeterli su kaynakları bırakabilmek adına tarımsal su yönetiminde ulusal bir seferberlik ilan edilmesi şarttır. Su kısıtı olan havzalarda yüksek su tüketen bitki desenlerinden vazgeçilmesi ve kuraklığa dayanıklı alternatif ürünlerin teşvik edilmesi bu stratejinin temelini oluşturmalıdır. Teknolojiyi doğayla uyum içinde kullanmayı başardığımız ölçüde tarımsal geleceğimizi güvence altına alabiliriz.</p>",
        "content_en": "<p>Global climate change and the resulting increased drought risks are increasing the pressure on our fresh water resources day by day. Considering that approximately 70 percent of the water consumed in the world is used for agricultural irrigation, it is clear that ensuring water efficiency in agriculture is not just a sectoral necessity, but a vital imperative. Abandoning wild irrigation methods and transitioning to smart systems that calculate every drop of water is the key to sustainability.</p><p>Smart irrigation technologies are modern systems equipped with soil moisture sensors, meteorological stations, and artificial intelligence-supported decision support mechanisms. Thanks to these systems, the amount of water the plant needs is analyzed instantaneously and irrigation is carried out at the exact time and in the right amount. In this way, not only is water waste prevented, but also factors that degrade soil quality such as rising groundwater and salinization caused by over-irrigation are prevented.</p><p>These applications of digitalization in agriculture may seem inaccessible for small producers due to initial investment costs. However, it is possible to popularize these technologies through cooperatives and state incentives. The savings in energy costs achieved by our farmers who switch to drip irrigation and pressurized irrigation infrastructure show that these investments pay for themselves in a very short time.</p><p>In order to leave fertile soil and sufficient water resources to future generations, it is imperative to declare a national mobilization in agricultural water management. Abandoning plant patterns that consume high amounts of water in basins with water constraints and encouraging drought-resistant alternative crops should form the basis of this strategy. We can secure our agricultural future to the extent that we succeed in using technology in harmony with nature.</p>",
        "summary": "Su israfını önlemek için yapay zeka destekli sulama yöntemlerinin önemi.",
        "summary_en": "The importance of AI-supported irrigation methods to prevent water waste.",
        "image_url": "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900&auto=format&fit=crop&q=80",
    },
    {
        "source_name": "Prof. Dr. Kemal Şahin",
        "title": "Stratejik Stok Yönetiminde Gıda Güvenliği",
        "title_en": "Food Security in Strategic Stock Management",
        "content": "<p>Gıda güvenliği, son yıllarda yaşanan jeopolitik krizler ve küresel salgın hastalıkların da etkisiyle artık ulusal bir beka meselesi haline gelmiştir. Kendi kendine yetebilme kavramı, sadece retorik bir heves olmaktan çıkıp, ülkelerin dış politika bağımsızlığını dahi etkileyen kritik bir parametre olmuştur. Bu noktada stratejik gıda stoklarının yönetimi, sadece bir depo yönetimi değil, çok boyutlu bir risk yönetimi sürecidir.</p><p>Devlet müdahale kurumlarının (TMO gibi) piyasaya olan regülatör etkisi, bu sürecin bel kemiğini oluşturur. Doğru zamanda yapılan müdahale alımları üreticiyi piyasa dalgalanmalarından korurken, tüketiciyi de fahiş fiyat artışlarından muhafaza eder. Ancak bu regülasyonun etkinliği, tamamen veriye dayalı arz-talep projeksiyonlarının isabetine bağlıdır.</p><p>Stok yönetiminde modern yaklaşımlar, sadece depolama miktarını değil, depoların lokasyonunu, lojistik maliyetlerini ve ürün kalitesinin korunmasını da merkeze alır. Lisanslı depoculuk sisteminin yaygınlaşması, bu anlamda atılmış en değerli adımlardan biridir. Çiftçinin ürününü modern silolarda güvenle saklayabilmesi ve bunu finansal bir araca dönüştürebilmesi, tarımsal ticaretin şeffaflaşmasına da büyük katkı sağlamaktadır.</p><p>Önümüzdeki dönemde, stratejik ürün deseninde (buğday, mısır, ayçiçeği vb.) sıfır fire hedefine odaklanan bir lojistik altyapısının kurulması elzemdir. Gıda güvenliğimiz, sadece topraktan aldığımız verimle değil, aynı zamanda o verimi kriz anlarına ne kadar hazırlıklı bir şekilde saklayabildiğimizle ölçülecektir.</p>",
        "content_en": "<p>Food security has now become an issue of national survival, especially with the impact of recent geopolitical crises and global pandemics. The concept of self-sufficiency has ceased to be merely a rhetorical desire and has become a critical parameter affecting even the foreign policy independence of countries. At this point, the management of strategic food stocks is not just warehouse management, but a multi-dimensional risk management process.</p><p>The regulatory impact of state intervention institutions (like TMO) on the market forms the backbone of this process. Intervention purchases made at the right time protect the producer from market fluctuations, while also protecting the consumer from exorbitant price increases. However, the effectiveness of this regulation depends entirely on the accuracy of data-driven supply-demand projections.</p><p>Modern approaches to stock management focus not only on the amount of storage but also on the location of the warehouses, logistics costs, and the preservation of product quality. The expansion of the licensed warehousing system is one of the most valuable steps taken in this sense. The ability of the farmer to safely store their product in modern silos and turn this into a financial instrument also contributes greatly to the transparency of agricultural trade.</p><p>In the coming period, it is essential to establish a logistics infrastructure that focuses on the zero-waste target in the strategic product pattern (wheat, corn, sunflower, etc.). Our food security will be measured not only by the yield we get from the soil, but also by how prepared we are to store that yield for moments of crisis.</p>",
        "summary": "Tarımsal ürünlerin lisanslı depoculuk ve devlet eliyle stratejik olarak saklanmasının önemi.",
        "summary_en": "The importance of strategically storing agricultural products through licensed warehousing and the state.",
        "image_url": "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=900&auto=format&fit=crop&q=80",
    },
    {
        "source_name": "Doç. Dr. Ayşe Gündüz",
        "title": "Kırsal Göçün Sosyolojisi ve Genç Çiftçiler",
        "title_en": "The Sociology of Rural Migration and Young Farmers",
        "content": "<p>Kırsaldan kente doğru yaşanan göç dalgası, tarımsal üretimi sadece ekonomik olarak değil, sosyolojik olarak da derinden sarsmaktadır. Köylerde yaşlanan nüfus, kuşaklar arası bilgi aktarımını kesintiye uğratmakta ve tarımsal mirasımızın yavaş yavaş kaybolmasına neden olmaktadır. Tarımı sadece bir geçim kaynağı değil, aynı zamanda kültürel bir kimlik olarak gören geleneksel yapının zayıflaması, bizi gelecekte daha büyük sorunlarla yüz yüze bırakacaktır.</p><p>Gençlerin tarımdan uzaklaşmasının temelinde yatan neden, sadece gelir düşüklüğü değil, aynı zamanda kırsaldaki yaşam standartlarının kentlere kıyasla yetersiz kalmasıdır. Eğitim, sağlık ve sosyalleşme imkanlarının kısıtlılığı, gençleri şehirlerin cazibesine kaptırmaktadır. Bu nedenle, genç çiftçileri toprağa döndürecek stratejiler sadece hibe ve kredi destekleriyle sınırlı kalamaz.</p><p>Kırsal yaşamın kalitesini artıracak bütüncül kalkınma modellerine ihtiyaç vardır. Akıllı köylerin (smart villages) kurulması, kırsalda yüksek hızlı internet erişiminin sağlanması ve teknoloji destekli tarımın özendirilmesi, yeni nesil çiftçilerin ilgisini çekecektir. Özellikle kooperatifçilik modelinin modernize edilerek gençlerin dinamizmine açılması, hem üretici örgütlenmesini güçlendirecek hem de kırsala sosyal bir canlılık katacaktır.</p><p>Unutmamalıyız ki; tarımı ayakta tutan sadece makine ve gübre değil, o toprağı işleyen insanın iradesidir. Gençlerimizi kırsalda mutlu ve müreffeh bir geleceğin mümkün olduğuna inandıramadığımız sürece, hiçbir tarım politikası tam anlamıyla başarıya ulaşamayacaktır.</p>",
        "content_en": "<p>The wave of migration from rural areas to the city deeply shakes agricultural production not only economically but also sociologically. The aging population in villages disrupts intergenerational knowledge transfer and causes our agricultural heritage to slowly disappear. The weakening of the traditional structure that sees agriculture not only as a source of livelihood but also as a cultural identity will face us with bigger problems in the future.</p><p>The underlying reason for young people\'s alienation from agriculture is not only low income, but also the inadequacy of rural living standards compared to cities. The limitations of education, health, and socialization opportunities draw young people to the allure of cities. Therefore, strategies to return young farmers to the land cannot be limited to grant and credit support alone.</p><p>Holistic development models that will increase the quality of rural life are needed. The establishment of smart villages, the provision of high-speed internet access in rural areas, and the encouragement of technology-supported agriculture will attract the attention of the new generation of farmers. In particular, modernizing the cooperative model and opening it to the dynamism of the youth will both strengthen producer organization and add social vitality to rural areas.</p><p>We must not forget that; what keeps agriculture alive is not just machinery and fertilizer, but the will of the human who works that land. As long as we cannot convince our young people that a happy and prosperous future is possible in the rural areas, no agricultural policy will fully succeed.</p>",
        "summary": "Genç nüfusun tarıma kazandırılması için kırsal yaşam standartlarının artırılması gerekliliği.",
        "summary_en": "The necessity of increasing rural living standards to bring the young population into agriculture.",
        "image_url": "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=900&auto=format&fit=crop&q=80",
    },
    {
        "source_name": "Caner Ekinci",
        "title": "Emtia Piyasalarındaki Çalkantılar: Buğday Raporu",
        "title_en": "Turbulence in Commodity Markets: Wheat Report",
        "content": "<p>Tarımsal emtia piyasaları, küresel iklim krizinin ve artan jeopolitik gerilimlerin gölgesinde son yılların en dalgalı dönemlerinden birini yaşıyor. Özellikle temel besin kaynağımız olan buğday fiyatlarındaki seyir, sadece üreticiyi değil, makroekonomik dengeleri de yakından ilgilendiriyor. Karadeniz havzasında yaşanan arz sıkıntıları ve majör üretici ülkelerin ihracat kısıtlamaları, küresel fiyatlarda belirgin bir oynaklığa neden olmuştur.</p><p>İç piyasaya baktığımızda ise, rekolte beklentilerinin iklimsel anomaliler nedeniyle sürekli revize edilmesi, fiyat oluşumunu zorlaştıran en büyük etken. Kuraklık endişesiyle birleşen yüksek girdi maliyetleri, üreticinin elindeki ürünün değerini koruma güdüsünü artırıyor. Bu noktada TMO\'nun (Toprak Mahsulleri Ofisi) açıklayacağı referans alım fiyatları, piyasanın yönünü belirlemede kilit rol oynayacaktır.</p><p>Gelecek projeksiyonlarına göre, dünyada buğday stok-kullanım oranlarının daralması, fiyatlar üzerindeki yukarı yönlü baskının bir süre daha devam edebileceğine işaret ediyor. Yatırımcılar ve büyük alıcılar (sanayiciler), vadeli işlem piyasalarında kendilerini koruma (hedging) mekanizmalarına daha fazla yönelmek zorundadır. Aksi takdirde, spot piyasadaki ani şoklar, gıda tedarik zincirinde onarılamaz hasarlara yol açabilir.</p><p>Sonuç olarak; emtia piyasalarındaki bu çalkantılı süreçten en az hasarla çıkmanın yolu, veriye dayalı stok yönetimi ve sözleşmeli üretim modellerinin teşvik edilmesinden geçmektedir. Çiftçiyi fiyat belirsizliğinden koruyacak sigorta mekanizmalarının güçlendirilmesi, sadece bugünün değil, yarının da güvencesidir.</p>",
        "content_en": "<p>Agricultural commodity markets are experiencing one of their most volatile periods in recent years in the shadow of the global climate crisis and increasing geopolitical tensions. The course of wheat prices, which is our basic food source, closely concerns not only the producer but also macroeconomic balances. Supply constraints in the Black Sea basin and export restrictions of major producing countries have caused significant volatility in global prices.</p><p>Looking at the domestic market, the continuous revision of harvest expectations due to climatic anomalies is the biggest factor complicating price formation. High input costs coupled with the fear of drought increase the producer\'s instinct to preserve the value of the product in their hands. At this point, the reference purchase prices to be announced by TMO (Turkish Grain Board) will play a key role in determining the market\'s direction.</p><p>According to future projections, the narrowing of wheat stock-to-use ratios in the world indicates that the upward pressure on prices may continue for a while. Investors and major buyers (industrialists) must increasingly turn to hedging mechanisms in futures markets. Otherwise, sudden shocks in the spot market can cause irreparable damage to the food supply chain.</p><p>In conclusion; the way to get out of this turbulent process in commodity markets with the least damage is through data-driven stock management and the encouragement of contracted production models. Strengthening insurance mechanisms that will protect the farmer from price uncertainty is the guarantee not only of today but also of tomorrow.</p>",
        "summary": "Buğday fiyatlarındaki küresel dalgalanmaların iç piyasaya etkileri.",
        "summary_en": "The effects of global fluctuations in wheat prices on the domestic market.",
        "image_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=900&auto=format&fit=crop&q=80",
    }
]

sql = 'INSERT INTO articles (id, title, title_en, content, content_en, summary, summary_en, image_url, status, content_type, source_name, is_hero, slug) VALUES\n'
values = []
for a in op_eds:
    vid = str(uuid.uuid4())
    vtitle = a['title'].replace("'", "''")
    vtitle_en = a['title_en'].replace("'", "''")
    vcontent = a['content'].replace("'", "''")
    vcontent_en = a['content_en'].replace("'", "''")
    vsum = a['summary'].replace("'", "''")
    vsum_en = a['summary_en'].replace("'", "''")
    vimg = a['image_url']
    vsrc = a['source_name'].replace("'", "''")
    vslug = str(uuid.uuid4())
    values.append(f"('{vid}', '{vtitle}', '{vtitle_en}', '{vcontent}', '{vcontent_en}', '{vsum}', '{vsum_en}', '{vimg}', 'published', 'text', '{vsrc}', false, '{vslug}')")
sql += ',\n'.join(values) + ';'

with open('seed_op_eds.sql', 'w') as f:
    f.write(sql)
print('SQL generated with slug')
